source 'https://rubygems.org'

gem 'activerecord'
gem 'haml'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem 'omniauth-identity'
gem 'omniauth-twitter'
gem 'settingslogic'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-flash'
gem 'sqlite3-ruby'