session_secret: 'fc683cd9ed1990ca2ea10b84e5e6fba048c24929'
database_path: 'sqlite:///db/foo.db'
providers:
  -
    strategy_name: 'twitter'
    id: 'BmKtqEX6sQPK3i7WqBkYiH5Df'
    secret: 'oy1WI8kUQ1hKOLLLcqTr4JExhIn9howwSeODNRpil5XXLWwoV8'
  -
    strategy_name: 'github'
    id: '8c3c4f0fdf312c81be5b'
    secret: '2c456360249305e1362f68613fcd1770dd4a1535'
  -
    strategy_name: 'facebook'
    id: '736768533019749'
    secret: '3779ebd7ee0a841f79d667cef36fa39c'
  -
    strategy_name: 'google_oauth2'
    id: '917375883211-9d6hat3keq95q1svll0s807ll2v6rs7u.apps.googleusercontent.com'
    secret: '8V17KvGQDpjgwRDO1_ccZAdY'
